def test_failing():
    assert False  # A purposely failing test
